[package]
name = "rust_solver"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_solver"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.171"
rayon = "1.8.0"
num_cpus = "1.16.0"
log = "0.4.20"
